export enum ValidationError {
    EmailMismatch = 'EmailMismatch',
    PasswordMismatch = 'PasswordMismatch',
    PasswordTooShort = 'PasswordTooShort',
    PasswordTooLong = 'PasswordTooLong',
    InvalidMobileNumber = 'InvalidMobileNumber',
    InvalidBarcode = 'InvalidBarcode',
    InvalidEmail = 'InvalidEmail',
    InvalidFirstName = 'InvalidFirstName',
    InvalidLastName = 'InvalidLastName',
    InvalidName = 'InvalidName',
    InvalidOTP = 'InvalidOTP',
    InvalidateHeightRange = 'InvalidateHeightRange',
    InvalidateWeightRange = 'InvalidateWeightRange',
    InvalidSpecialCharacters = 'InvalidSpecialCharacters',
    InvalidPostalCode = 'InvalidPostalCode',
    InvalidCreditCard = 'InvalidCreditCard',
    InvalidExpiryDate = 'InvalidExpiryDate',
    InvalidCVV = 'InvalidCVV',
    InvalidDocumentNumber = 'InvalidDocumentNumber',
}
